services:
  mosaic:
    image: whittkaertech/mosaicjs
    build: .
    container_name: whittakertech_mosaicjs
    volumes:
      - .:/app
    stdin_open: true
    tty: true
  mosaic-docs:
    image: whittkaertech/mosaicjs
    build: .
    working_dir: /app
    command: npm run docs -- --host 0.0.0.0 --port 5173 --no-open
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    stdin_open: true
    tty: true

