import fs from "fs";
import path from "path";

/**
 * AUTO-GENERATED DOCUMENTATION SCRIPT
 *
 * Source of truth:
 *   src/css/contract.ts → DEFAULT_CSS_CLASS_CONTRACT
 *
 * Output:
 *   docs/documentation/_generated/default-css.css
 */

const sourceFile = path.resolve("src/css/contract.ts");
const outPath = path.resolve(
  "docs/documentation/_generated/default-css.css"
);

const source = fs.readFileSync(sourceFile, "utf8");

// Match DEFAULT_CSS_CLASS_CONTRACT = Object.freeze({ ... })
const match = source.match(
  /export const DEFAULT_CSS_CLASS_CONTRACT\s*=\s*Object\.freeze\(\s*({[\s\S]*?})\s*(?:as\s+const\s+satisfies\s+\w+)?\s*\)/m
);

if (!match) {
  throw new Error(
    "Could not find DEFAULT_CSS_CLASS_CONTRACT in src/css/contract.ts"
  );
}

const objectBody = match[1];

// Match entries like:
// active: "mosaic--active",
const entries = [...objectBody.matchAll(
  /(\w+)\s*:\s*["'`](.+?)["'`]/g
)];

if (entries.length === 0) {
  throw new Error(
    "DEFAULT_CSS_CLASS_CONTRACT was found but no entries could be parsed"
  );
}

const lines: string[] = [];

lines.push("/*");
lines.push(" * AUTO-GENERATED FILE — DO NOT EDIT");
lines.push(" *");
lines.push(" * Source: src/css/contract.ts (DEFAULT_CSS_CLASS_CONTRACT)");
lines.push(" * Generated by: scripts/generate-docs/default-css-block.ts");
lines.push(" */");
lines.push("");

for (const [, key, className] of entries) {
  lines.push(`/* ${key} */`);
  lines.push(`.${className} {`);
  lines.push("  /* optional */");
  lines.push("}");
  lines.push("");
}

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, lines.join("\n"), "utf8");

console.log("✓ Default CSS reference generated");
