import fs from "fs";
import path from "path";

/**
 * AUTO-GENERATED DOCUMENTATION SCRIPT
 *
 * Source of truth:
 *   src/drag/lifecycle.ts → DRAG_HOOK_STATES
 *
 * Output:
 *   docs/guides/_generated/drag-hook-table.md
 */

const sourceFile = path.resolve("src/drag/lifecycle.ts");
const outPath = path.resolve(
  "docs/guides/_generated/drag-hook-table.md"
);

const source = fs.readFileSync(sourceFile, "utf8");

// Match Object.freeze({ ... } as const)
const match = source.match(
  /export const DRAG_HOOK_STATES\s*=\s*Object\.freeze\(\s*({[\s\S]*?})\s*as const\s*\)/m
);

if (!match) {
  throw new Error(
    "Could not find DRAG_HOOK_STATES in src/drag/lifecycle.ts"
  );
}

const objectBody = match[1];

// Extract lines like:
// onDragStart: MosaicState.PointerDown,
const entries = [...objectBody.matchAll(
  /(\w+)\s*:\s*MosaicState\.(\w+)/g
)];

if (entries.length === 0) {
  throw new Error(
    "DRAG_HOOK_STATES was found but no entries could be parsed"
  );
}

const lines: string[] = [];

lines.push("<!--");
lines.push("AUTO-GENERATED FILE — DO NOT EDIT");
lines.push("Source: src/drag/lifecycle.ts (DRAG_HOOK_STATES)");
lines.push("Generated by: scripts/generate-docs/drag-hook-table.ts");
lines.push("-->");
lines.push("");
lines.push("| Hook | Guaranteed State |");
lines.push("|------|------------------|");

for (const [, hook, state] of entries) {
  lines.push(`| \`${hook}\` | \`${state}\` |`);
}

lines.push("");

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, lines.join("\n"), "utf8");

console.log("✓ Drag hook table generated");
